import localFont from "next/font/local";
import "./globals.css";

const sourGummy = localFont({
  src: "./fonts/SourGummy_Expanded-Bold.ttf",
  variable: "--font-sour-gummy",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sourGummy.variable}`}
        style={{
          fontFamily: "sans-serif",
          fontWeight: 800,
          fontStyle: "normal",
        }}
      >
        {children}
      </body>
    </html>
  );
}
