import localFont from "next/font/local";
import "./globals.css";

const lovely = localFont({
  src: "./fonts/LOVELY.otf",
  variable: "--font-lovely",
  weight: "700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lovely.variable}`}>{children}</body>
    </html>
  );
}
